Day4/config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root "articles#index"

  # Root path



  resources :articles do
    resources :comments
    member do 
      post 'report', to: "articles#report"
    end
  end

end

Day4/app/models/article.rb
class Article < ApplicationRecord
  include Visible
  
  has_one_attached :avatar
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  validates :reports_count, presence: true
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

Day4/app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

Day4/app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

Day4/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

Day4/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

Day4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

  

Day4/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  before_action :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]
 

  def index
      @articles = Article.where(status: 'public')
    
  end
  
  
  def show
      @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.reports_count ||= 0
    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end
  

  def edit
    redirect_to articles_path, alert: "Access Denied" unless @article.user_id == current_user.id
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  def report
    @article = Article.find(params[:id])
    @article.increment!(:reports_count)

    if @article.reports_count >= 3
      @article.update(status: "archived")
    end
    redirect_to root_path, notice: "Article reported successfully."
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :status,:avatar)
  end
end

Day4/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article), status: :see_other
    end
  
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end
  end
  

Day4/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  protected

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

Day4/app/helpers/articles_helper.rb
module ArticlesHelper
end

Day4/app/helpers/comments_helper.rb
module CommentsHelper
end

Day4/app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

<div>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
</div>
 <%= form.file_field :avatar %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

Day4/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

Day4/app/views/articles/index.html.erb
<h1>Articles</h1>

<%= "Our blog has #{Article.public_count} articles and counting!" %>

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<% if user_signed_in? %>
  <%= link_to "New Article", new_article_path %>
<%= button_to "Logout", destroy_user_session_path, method: :delete%>
<% else %>
  <%= button_to "Login", new_user_session_path %>
<% end %>

Day4/app/views/articles/new.html.erb
<h1>New Article</h1>


<%= render "form", article: @article %>

Day4/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>
<p>avatar</p>

<%= image_tag @article.avatar if @article.avatar.attached? %>



<% if user_signed_in? %>
<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>


    <%= link_to "Report", report_article_path(@article), data: {
      turbo_method: :post,
      turbo_confirm: "Are you sure?"} %>
<% end %>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

Day4/app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

Day4/app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
</p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

Day4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>